name: Build Matrix Rust SDK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-ios
          override: true

      - name: Install iOS target
        run: rustup target add aarch64-apple-ios

      - name: Build
        working-directory: ./
        env:
          CARGO_TARGET_AARCH64_APPLE_IOS_RUSTFLAGS: -Clinker=/usr/bin/clang
          AARCH64_APPLE_IOS_CC: /usr/bin/clang
          IPHONEOS_DEPLOYMENT_TARGET: 17.5
        run: cargo build --target aarch64-apple-ios
